config/routes.rb
SoapBox::Application.routes.draw do

  resources :dislikes

  resources :likes

  resources :comments

  resources :votes
  resources :choices
  resources :questions
  resources :users
  resources :sessions

  get 'choices/vote'

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signup',  to: 'users#new'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :content, :user_id, :choices_attributes
  belongs_to :user
  has_many :choices
  accepts_nested_attributes_for :choices

  default_scope order: 'questions.created_at DESC'
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @questions }
    end
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
    @question = Question.find(params[:id])
	@choice0 = @question.choices[0]
	@choice1 = @question.choices[1]
#	@comment0 = @choice0.comments.build(:choice_id => @choice0.id, :user_id => current_user.id)
#	@comment1 = @choice1.comments.build(:choice_id => @choice1.id, :user_id => current_user.id)
#	@comment0 = @choice0.comments.build()
#	@comment1 = @choice1.comments.build()

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/new
  # GET /questions/new.json
  def new
    @question = current_user.questions.new
	2.times do
	  @question.choices.build
	end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @question }
    end
  end

  # GET /questions/1/edit
  def edit
    @question = Question.find(params[:id])
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = current_user.questions.new(params[:question])

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: params.inspect}#'Question was successfully created.' }
        format.json { render json: @question, status: :created, location: @question }
      else
        format.html { render action: "new" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /questions/1
  # PUT /questions/1.json
  def update
    @question = Question.find(params[:id])

    respond_to do |format|
      if @question.update_attributes(params[:question])
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question = Question.find(params[:id])
    @question.destroy

    respond_to do |format|
      format.html { redirect_to :back }
      format.json { head :no_content }
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_choice_column.html.erb
<div class="bubble">			
	<%= render @choice %>
	<%= @choice.description%>
	<br>
	<br>
	<%= render @choice.comments %>
	<div class="bubble">
		<%= render 'comment_form' %>
	</div>
</div>

app/views/questions/_choices_fields.html.erb
  <div class="field">
    <%= f.label "Enter Option:" %>
    <%= f.text_field :content %><br />
  </div>

  <div class="field">
    <%= f.label "Option Desctiption:" %>
    <%= f.text_field :description %><br />
  </div>

<br>
<br>

app/views/questions/_comment_fields.html.erb
<%= f.text_area :content, placeholder: "Have a comment to add?", rows: 3 %>
<%= hidden_field_tag(:choice_id, @choice.id) %>
<%= hidden_field_tag(:user_id, current_user.id) %>

app/views/questions/_comment_form.html.erb
<%= form_for(@comment1 = @choice.comments.build(:choice_id => @choice.id)) do |f| %>

  <%= render 'comment_fields', f: f %>

  <%= f.submit "Add Comment", :choice_id => @choice.id, class: "btn btn-large btn-primary" %>
<% end %>

app/views/questions/_fields.html.erb
  <div class="field">
    <%= f.label "What are you wondering today?" %>
    <%= f.text_field :content %><br /><br />
  </div>

  <p><b> And what are the alternatives to choose from? </b></p>

  <%= f.fields_for :choices do |builder| %>
	<%= render "choices_fields", :f => builder %>
  <% end %>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "What are you wondering today?" %>
    <%= f.text_field :content %><br /><br />
  </div>

  <p><b> And what are the alternatives to choose from? </b></p>

  <%= f.fields_for :choices do |builder| %>
	<%= render "choices_fields", :f => builder %>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/_question.html.erb
<div class="bubble">
	<div class="container-fluid">
		<div class="row-fluid center">
			<div class="span 11" offset0" align="center">
				<s2><b><%= link_to question.content, question_path(question) %></b></s2>
			</div>
			<br>
			<br>
			<div class="span5 offset0" align="left">
				<% choice = question.choices[0] %>
				<%= button_to [choice.content, " (",choice.votes.length,")"], {:controller => :votes, :action => :create, :choice_id => choice.id}, :class => "buttonTo btn" %>
			</div>
			<div class="span5 offset1" align="right">
				<% choice = question.choices[1] %>
				<%= button_to ["(",choice.votes.length,") ", choice.content], {:controller => :votes, :action => :create, :choice_id => choice.id}, :class => "buttonTo btn" %>
			</div>
		</div>
		<div class="span3 offset0" align="left">
			<% if question.user == current_user %>
				<%= gravatar_for(question.user, size:15) %><%= link_to '*Delete Question*', question, method: :delete, data: { confirm: 'Are you sure?' } %>
			<% else %>
				<%= link_to gravatar_for(question.user, size:15), user_path(question.user) %><%= link_to question.user.username, user_path(question.user) %>
			<% end %>
		</div>
		<div class="span3 offset0" align="right">
			<%= link_to pluralize((question.choices[0].comments.length+question.choices[1].comments.length).to_s(),"comment"), question_path(question) %>
		</div>
	</div>
</div>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <tr>
    <th>Content</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @questions.each do |question| %>
  <tr>
    <td><%= question.content %></td>
    <td><%= question.user_id %></td>
    <td><%= link_to 'Show', question %></td>
    <td><%= link_to 'Edit', edit_question_path(question) %></td>
    <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<% provide(:title, 'Post a Question') %>
<div class="hero-unit">
<h1>Post a Question</h1>
<br>
<br>
<br>
<div class="row">
  <div class="span7 offset2">
    <%= form_for(@question) do |f| %>
      <%= render 'fields', f: f %>
      <%= f.submit "Post Question", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>
</div>

app/views/questions/show.html.erb
<p id="notice"><% notice %></p>

<div class="bubble">
	<div class="container-fluid">
		<div class="row-fluid center">
			<div class="span 10" offset1">
				<h1><b><%= @question.content %></b></h1>
				<% if @question.user == current_user %>
					<div class="span6 offset0" align="left">
						<s-3><%= link_to "View All Your Questions", user_path(@question.user) %></s-3>
					</div>
					<div class="span5 offset0" align="right">
						<s-3><%= link_to '*Delete This Question*', @question, method: :delete, data: { confirm: 'Are you sure?' } %></s-3>
					</div>
				<% else %>
					<s-3><%= link_to "*show all questions from user*", user_path(@question.user) %></s-3>
				<% end %>
			</div>
		</div>
	</div>
</div>
<br>
<div class="container-fluid">
	<div class="row-fluid center">
		<div class="span6 offset0">
			<% @choice = @question.choices[0] %>
			<%= render 'choice_column' %>
		</div>
		<div class="span6 offset0">
			<% @choice = @question.choices[1] %>
			<%= render 'choice_column' %>
		</div>
	</div>
</div>

<% link_to 'Edit', edit_question_path(@question) %> 
<% link_to 'Back', questions_path %>