config/routes.rb
SoapBox::Application.routes.draw do

  resources :dislikes

  resources :likes

  resources :comments

  resources :votes
  resources :choices
  resources :questions
  resources :users
  resources :sessions

  get 'choices/vote'

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signup',  to: 'users#new'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/dislike.rb
class Dislike < ActiveRecord::Base
  attr_accessible :comment_id, :user_id
  belongs_to :comment
  belongs_to :user
end

app/controllers/dislikes_controller.rb
class DislikesController < ApplicationController
  # GET /dislikes
  # GET /dislikes.json
  def index
    @dislikes = Dislike.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dislikes }
    end
  end

  # GET /dislikes/1
  # GET /dislikes/1.json
  def show
    @dislike = Dislike.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @dislike }
    end
  end

  # GET /dislikes/new
  # GET /dislikes/new.json
  def new
    @dislike = Dislike.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dislike }
    end
  end

  # GET /dislikes/1/edit
  def edit
    @dislike = Dislike.find(params[:id])
  end

  # POST /dislikes
  # POST /dislikes.json
  def create
    @dislike = Dislike.new(:comment_id => params[:comment_id], :user_id => current_user.id)

    respond_to do |format|
      if @dislike.save
        format.html { redirect_to :back, notice: 'Dislike was successfully created.' }
#        format.json { render json: @dislike, status: :created, location: @dislike }
#      else
#        format.html { render action: "new" }
#        format.json { render json: @dislike.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dislikes/1
  # PUT /dislikes/1.json
  def update
    @dislike = Dislike.find(params[:id])

    respond_to do |format|
      if @dislike.update_attributes(params[:dislike])
        format.html { redirect_to @dislike, notice: 'Dislike was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dislike.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dislikes/1
  # DELETE /dislikes/1.json
  def destroy
    @dislike = Dislike.find(params[:id])
    @dislike.destroy

    respond_to do |format|
      format.html { redirect_to dislikes_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dislikes_helper.rb
module DislikesHelper
end

app/views/dislikes/_form.html.erb
<%= form_for(@dislike) do |f| %>
  <% if @dislike.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dislike.errors.count, "error") %> prohibited this dislike from being saved:</h2>

      <ul>
      <% @dislike.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :comment_id %><br />
    <%= f.number_field :comment_id %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dislikes/edit.html.erb
<h1>Editing dislike</h1>

<%= render 'form' %>

<%= link_to 'Show', @dislike %> |
<%= link_to 'Back', dislikes_path %>

app/views/dislikes/index.html.erb
<h1>Listing dislikes</h1>

<table>
  <tr>
    <th>Comment</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dislikes.each do |dislike| %>
  <tr>
    <td><%= dislike.comment_id %></td>
    <td><%= dislike.user_id %></td>
    <td><%= link_to 'Show', dislike %></td>
    <td><%= link_to 'Edit', edit_dislike_path(dislike) %></td>
    <td><%= link_to 'Destroy', dislike, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dislike', new_dislike_path %>

app/views/dislikes/new.html.erb
<h1>New dislike</h1>

<%= render 'form' %>

<%= link_to 'Back', dislikes_path %>

app/views/dislikes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Comment:</b>
  <%= @dislike.comment_id %>
</p>

<p>
  <b>User:</b>
  <%= @dislike.user_id %>
</p>


<%= link_to 'Edit', edit_dislike_path(@dislike) %> |
<%= link_to 'Back', dislikes_path %>