config/routes.rb
SoapBox::Application.routes.draw do

  resources :dislikes

  resources :likes

  resources :comments

  resources :votes
  resources :choices
  resources :questions
  resources :users
  resources :sessions

  get 'choices/vote'

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signup',  to: 'users#new'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/models/choice.rb
class Choice < ActiveRecord::Base
  attr_accessible :content, :question_id, :description
  belongs_to :question
  has_many :votes
  has_many :comments
end

app/controllers/choices_controller.rb
class ChoicesController < ApplicationController
  # GET /choices
  # GET /choices.json

  def vote
	@choice = Choice.find(params[:id])
	vote = @choice.votes.build

    respond_to do |format|
      if vote.save
        format.html { redirect_to :back, notice: 'Vote was successfully created.' }
        format.json { render json: :back, status: :created, location: @question }
#      else
#        format.html { render action: "new" }
#        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  def index
    @choices = Choice.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @choices }
    end
  end

  # GET /choices/1
  # GET /choices/1.json
  def show
    @choice = Choice.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @choice }
    end
  end

  # GET /choices/new
  # GET /choices/new.json
  def new
    @choice = Choice.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @choice }
    end
  end

  # GET /choices/1/edit
  def edit
    @choice = Choice.find(params[:id])
  end

  # POST /choices
  # POST /choices.json
  def create
    @choice = Choice.new(params[:choice])

    respond_to do |format|
      if @choice.save
        format.html { redirect_to @choice, notice: 'Choice was successfully created.' }
        format.json { render json: @choice, status: :created, location: @choice }
      else
        format.html { render action: "new" }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /choices/1
  # PUT /choices/1.json
  def update
    @choice = Choice.find(params[:id])

    respond_to do |format|
      if @choice.update_attributes(params[:choice])
        format.html { redirect_to @choice, notice: 'Choice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @choice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /choices/1
  # DELETE /choices/1.json
  def destroy
    @choice = Choice.find(params[:id])
    @choice.destroy

    respond_to do |format|
      format.html { redirect_to choices_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/choices_helper.rb
module ChoicesHelper
end

app/views/choices/_choice.html.erb
<%= button_to [choice.content, "  (",choice.votes.length,")"], {:controller => :votes, :action => :create, :choice_id => choice.id}, :class => "buttonTo btn-large" %>

app/views/choices/_form.html.erb
<%= form_for(@choice) do |f| %>
  <% if @choice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@choice.errors.count, "error") %> prohibited this choice from being saved:</h2>

      <ul>
      <% @choice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :question_id %><br />
    <%= f.number_field :question_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/choices/edit.html.erb
<h1>Editing choice</h1>

<%= render 'form' %>

<%= link_to 'Show', @choice %> |
<%= link_to 'Back', choices_path %>

app/views/choices/index.html.erb
<h1>Listing choices</h1>

<table>
  <tr>
    <th>Content</th>
    <th>Question</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @choices.each do |choice| %>
  <tr>
    <td><%= choice.content %></td>
    <td><%= choice.question_id %></td>
    <td><%= link_to 'Show', choice %></td>
    <td><%= link_to 'Edit', edit_choice_path(choice) %></td>
    <td><%= link_to 'Destroy', choice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Choice', new_choice_path %>

app/views/choices/new.html.erb
<h1>New choice</h1>

<%= render 'form' %>

<%= link_to 'Back', choices_path %>

app/views/choices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @choice.content %>
</p>

<p>
  <b>Question:</b>
  <%= @choice.question_id %>
</p>


<%= link_to 'Edit', edit_choice_path(@choice) %> |
<%= link_to 'Back', choices_path %>