config/routes.rb
SoapBox::Application.routes.draw do

  resources :dislikes

  resources :likes

  resources :comments

  resources :votes
  resources :choices
  resources :questions
  resources :users
  resources :sessions

  get 'choices/vote'

  root to: 'static_pages#home'

  match '/signup',  to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  match '/signup',  to: 'users#new'
  match '/help',    to: 'static_pages#help'
  match '/about',   to: 'static_pages#about'
  match '/contact', to: 'static_pages#contact'

end

app/views/layouts/_footer.html.erb
<br /><br />
<footer class="footer">

    <div class="container">
  <small>
    site by 
    <a href="http://www.ncheney.com">Nick Cheney</a>
  </small>
  <nav>
    <ul class="span2 offset8">
      <li><%= link_to "About",   about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://www.peoplessoapbox.com", target="_blank">Info</a></li>
    </ul>
  </nav>

</div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "SoapBox", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if signed_in? %>
            <li><%= link_to "All Users", users_path %></li>
<li><%= link_to "New Question", new_question_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <%= gravatar_for current_user , options = {size: 25} %> <%= current_user.username %> <!b class="caret"><!/b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_user %></li>
                <li><%= link_to "Settings", edit_user_path(current_user) %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
<li><%= link_to "My Page", current_user %></li>
<li><% link_to "Account Settings", edit_user_path(current_user) %>
    <a href="http://gravatar.com/emails" target="_blank" >Change Image</a> </li>
<li><%= link_to "Sign out", signout_path, method: "delete" %></li>
          <% else %>
            <li><%= link_to "Sign in", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>    
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>  
    </div>
  </body>
</html>